### ISSUE TITLE
Enlever l'onglet Formgrader pour les élèves

### ISSUE THREAD

**Issue by Mad31** [wawachief/jupyterhubDocker#2]
Possibilité de ne pas avoir l'onglet formgrader pour les élèves :
jupyter nbextension disable --sys-prefix formgrader/main --section=tree
jupyter serverextension disable --sys-prefix nbgrader.server_extensions.formgrader

et de refaire avec un enable pour les profs.

mais lorsque je fais ça en prof1 , il me répond 
jupyter not found

**Comment by wawachief** [comment]
Le pb a été réglé lors de la mise a jour précédente
